# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"$\n\x08Operands\x12\x0b\n\x03op1\x18\x01 \x01(\x05\x12\x0b\n\x03op2\x18\x02 \x01(\x05\"\x17\n\x06Result\x12\r\n\x05value\x18\x01 \x01(\x05\x32m\n\nCalculator\x12\x1b\n\x03\x41\x64\x64\x12\t.Operands\x1a\x07.Result\"\x00\x12 \n\x08Subtract\x12\t.Operands\x1a\x07.Result\"\x00\x12 \n\x08Multiply\x12\t.Operands\x1a\x07.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OPERANDS']._serialized_start=20
  _globals['_OPERANDS']._serialized_end=56
  _globals['_RESULT']._serialized_start=58
  _globals['_RESULT']._serialized_end=81
  _globals['_CALCULATOR']._serialized_start=83
  _globals['_CALCULATOR']._serialized_end=192
# @@protoc_insertion_point(module_scope)
